# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a270df65a31fc4c694814c01d0a8fc051fc00c765cae13de5d9b8c6bf9e69371539f40e71c01d68aad3425e58ec7a43980c1d04f62dc0e242d151dec1861bfbd

test:
  secret_key_base: bbbffee39d2f0db6c9b535228e5fde43a4ae75a3f595d9e24177cf32718d9d9dfde981986441862d0fa018616eee30f5f1484d9c8eb8ddb5cdddfb39cdb56f0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
